import numpy as np

study_of_interest = "PowerFlow"
simulation_time = 0.1
include_capacitance_of_lines = True
nominal_frequency = 60
slack_bus = "150"

line_seg_data = [
    # {"Node_A": 150, "Node_B": 610, "Length_ft": 0, "config": "XFMR-1"},
    {"Node_A": 1, "Node_B": 2, "Length_ft": 175, "config": "10"},
    {"Node_A": 1, "Node_B": 3, "Length_ft": 250, "config": "11"},
    {"Node_A": 1, "Node_B": 7, "Length_ft": 300, "config": "1"},
    {"Node_A": 3, "Node_B": 4, "Length_ft": 200, "config": "11"},
    {"Node_A": 3, "Node_B": 5, "Length_ft": 325, "config": "11"},
    {"Node_A": 5, "Node_B": 6, "Length_ft": 250, "config": "11"},
    {"Node_A": 7, "Node_B": 8, "Length_ft": 200, "config": "1"},
    {"Node_A": 8, "Node_B": 12, "Length_ft": 225, "config": "10"},
    {"Node_A": 8, "Node_B": 9, "Length_ft": 225, "config": "9"},
    {"Node_A": 8, "Node_B": 13, "Length_ft": 300, "config": "1"},
    {"Node_A": 901, "Node_B": 14, "Length_ft": 425, "config": "9"},
    {"Node_A": 13, "Node_B": 34, "Length_ft": 150, "config": "11"},
    {"Node_A": 13, "Node_B": 18, "Length_ft": 825, "config": "2"},
    {"Node_A": 14, "Node_B": 11, "Length_ft": 250, "config": "9"},
    {"Node_A": 14, "Node_B": 10, "Length_ft": 250, "config": "9"},
    {"Node_A": 15, "Node_B": 16, "Length_ft": 375, "config": "11"},
    {"Node_A": 15, "Node_B": 17, "Length_ft": 350, "config": "11"},
    {"Node_A": 18, "Node_B": 19, "Length_ft": 250, "config": "9"},
    {"Node_A": 18, "Node_B": 21, "Length_ft": 300, "config": "2"},
    {"Node_A": 19, "Node_B": 20, "Length_ft": 325, "config": "9"},
    {"Node_A": 21, "Node_B": 22, "Length_ft": 525, "config": "10"},
    {"Node_A": 21, "Node_B": 23, "Length_ft": 250, "config": "2"},
    {"Node_A": 23, "Node_B": 24, "Length_ft": 550, "config": "11"},
    {"Node_A": 23, "Node_B": 25, "Length_ft": 275, "config": "2"},
    {"Node_A": 2501, "Node_B": 26, "Length_ft": 350, "config": "7"},
    {"Node_A": 25, "Node_B": 28, "Length_ft": 200, "config": "2"},
    {"Node_A": 26, "Node_B": 27, "Length_ft": 275, "config": "7"},
    {"Node_A": 26, "Node_B": 31, "Length_ft": 225, "config": "11"},
    {"Node_A": 27, "Node_B": 33, "Length_ft": 500, "config": "9"},
    {"Node_A": 28, "Node_B": 29, "Length_ft": 300, "config": "2"},
    {"Node_A": 29, "Node_B": 30, "Length_ft": 350, "config": "2"},
    {"Node_A": 30, "Node_B": 250, "Length_ft": 200, "config": "2"},
    {"Node_A": 31, "Node_B": 32, "Length_ft": 300, "config": "11"},
    {"Node_A": 34, "Node_B": 15, "Length_ft": 100, "config": "11"},
    {"Node_A": 35, "Node_B": 36, "Length_ft": 650, "config": "8"},
    {"Node_A": 35, "Node_B": 40, "Length_ft": 250, "config": "1"},
    {"Node_A": 36, "Node_B": 37, "Length_ft": 300, "config": "9"},
    {"Node_A": 36, "Node_B": 38, "Length_ft": 250, "config": "10"},
    {"Node_A": 38, "Node_B": 39, "Length_ft": 325, "config": "10"},
    {"Node_A": 40, "Node_B": 41, "Length_ft": 325, "config": "11"},
    {"Node_A": 40, "Node_B": 42, "Length_ft": 250, "config": "1"},
    {"Node_A": 42, "Node_B": 43, "Length_ft": 500, "config": "10"},
    {"Node_A": 42, "Node_B": 44, "Length_ft": 200, "config": "1"},
    {"Node_A": 44, "Node_B": 45, "Length_ft": 200, "config": "9"},
    {"Node_A": 44, "Node_B": 47, "Length_ft": 250, "config": "1"},
    {"Node_A": 45, "Node_B": 46, "Length_ft": 300, "config": "9"},
    {"Node_A": 47, "Node_B": 48, "Length_ft": 150, "config": "4"},
    {"Node_A": 47, "Node_B": 49, "Length_ft": 250, "config": "4"},
    {"Node_A": 49, "Node_B": 50, "Length_ft": 250, "config": "4"},
    {"Node_A": 50, "Node_B": 51, "Length_ft": 250, "config": "4"},
    {"Node_A": 51, "Node_B": 151, "Length_ft": 500, "config": "4"},
    {"Node_A": 52, "Node_B": 53, "Length_ft": 200, "config": "1"},
    {"Node_A": 53, "Node_B": 54, "Length_ft": 125, "config": "1"},
    {"Node_A": 54, "Node_B": 55, "Length_ft": 275, "config": "1"},
    {"Node_A": 54, "Node_B": 57, "Length_ft": 350, "config": "3"},
    {"Node_A": 55, "Node_B": 56, "Length_ft": 275, "config": "1"},
    {"Node_A": 57, "Node_B": 58, "Length_ft": 250, "config": "10"},
    {"Node_A": 57, "Node_B": 60, "Length_ft": 750, "config": "3"},
    {"Node_A": 58, "Node_B": 59, "Length_ft": 250, "config": "10"},
    {"Node_A": 60, "Node_B": 61, "Length_ft": 550, "config": "5"},
    {"Node_A": 611, "Node_B": 610, "Length_ft": 0, "config": "XFM-1"},
    # {"Node_A": 611, "Node_B": 610, "Length_ft": 1, "config": "5"},
    {"Node_A": 60, "Node_B": 62, "Length_ft": 250, "config": "12"},
    {"Node_A": 62, "Node_B": 63, "Length_ft": 175, "config": "12"},
    {"Node_A": 63, "Node_B": 64, "Length_ft": 350, "config": "12"},
    {"Node_A": 64, "Node_B": 65, "Length_ft": 425, "config": "12"},
    {"Node_A": 65, "Node_B": 66, "Length_ft": 325, "config": "12"},
    {"Node_A": 67, "Node_B": 68, "Length_ft": 200, "config": "9"},
    {"Node_A": 67, "Node_B": 72, "Length_ft": 275, "config": "3"},
    {"Node_A": 67, "Node_B": 97, "Length_ft": 250, "config": "3"},
    {"Node_A": 68, "Node_B": 69, "Length_ft": 275, "config": "9"},
    {"Node_A": 69, "Node_B": 70, "Length_ft": 325, "config": "9"},
    {"Node_A": 70, "Node_B": 71, "Length_ft": 275, "config": "9"},
    {"Node_A": 72, "Node_B": 73, "Length_ft": 275, "config": "11"},
    {"Node_A": 72, "Node_B": 76, "Length_ft": 200, "config": "3"},
    {"Node_A": 73, "Node_B": 74, "Length_ft": 350, "config": "11"},
    {"Node_A": 74, "Node_B": 75, "Length_ft": 400, "config": "11"},
    {"Node_A": 76, "Node_B": 77, "Length_ft": 400, "config": "6"},
    {"Node_A": 76, "Node_B": 86, "Length_ft": 700, "config": "3"},
    {"Node_A": 77, "Node_B": 78, "Length_ft": 100, "config": "6"},
    {"Node_A": 78, "Node_B": 79, "Length_ft": 225, "config": "6"},
    {"Node_A": 78, "Node_B": 80, "Length_ft": 475, "config": "6"},
    {"Node_A": 80, "Node_B": 81, "Length_ft": 475, "config": "6"},
    {"Node_A": 81, "Node_B": 82, "Length_ft": 250, "config": "6"},
    {"Node_A": 81, "Node_B": 84, "Length_ft": 675, "config": "11"},
    {"Node_A": 82, "Node_B": 83, "Length_ft": 250, "config": "6"},
    {"Node_A": 84, "Node_B": 85, "Length_ft": 475, "config": "11"},
    {"Node_A": 86, "Node_B": 87, "Length_ft": 450, "config": "6"},
    {"Node_A": 87, "Node_B": 88, "Length_ft": 175, "config": "9"},
    {"Node_A": 87, "Node_B": 89, "Length_ft": 275, "config": "6"},
    {"Node_A": 89, "Node_B": 90, "Length_ft": 225, "config": "10"},
    {"Node_A": 89, "Node_B": 91, "Length_ft": 225, "config": "6"},
    {"Node_A": 91, "Node_B": 92, "Length_ft": 300, "config": "11"},
    {"Node_A": 91, "Node_B": 93, "Length_ft": 225, "config": "6"},
    {"Node_A": 93, "Node_B": 94, "Length_ft": 275, "config": "9"},
    {"Node_A": 93, "Node_B": 95, "Length_ft": 300, "config": "6"},
    {"Node_A": 95, "Node_B": 96, "Length_ft": 200, "config": "10"},
    {"Node_A": 97, "Node_B": 98, "Length_ft": 275, "config": "3"},
    {"Node_A": 98, "Node_B": 99, "Length_ft": 550, "config": "3"},
    {"Node_A": 99, "Node_B": 100, "Length_ft": 300, "config": "3"},
    {"Node_A": 100, "Node_B": 450, "Length_ft": 800, "config": "3"},
    {"Node_A": 101, "Node_B": 102, "Length_ft": 225, "config": "11"},
    {"Node_A": 101, "Node_B": 105, "Length_ft": 275, "config": "3"},
    {"Node_A": 102, "Node_B": 103, "Length_ft": 325, "config": "11"},
    {"Node_A": 103, "Node_B": 104, "Length_ft": 700, "config": "11"},
    {"Node_A": 105, "Node_B": 106, "Length_ft": 225, "config": "10"},
    {"Node_A": 105, "Node_B": 108, "Length_ft": 325, "config": "3"},
    {"Node_A": 106, "Node_B": 107, "Length_ft": 575, "config": "10"},
    {"Node_A": 108, "Node_B": 109, "Length_ft": 450, "config": "9"},
    {"Node_A": 108, "Node_B": 300, "Length_ft": 1000, "config": "3"},
    {"Node_A": 109, "Node_B": 110, "Length_ft": 300, "config": "9"},
    {"Node_A": 110, "Node_B": 111, "Length_ft": 575, "config": "9"},
    {"Node_A": 110, "Node_B": 112, "Length_ft": 125, "config": "9"},
    {"Node_A": 112, "Node_B": 113, "Length_ft": 525, "config": "9"},
    {"Node_A": 113, "Node_B": 114, "Length_ft": 325, "config": "9"},
    {"Node_A": 135, "Node_B": 35, "Length_ft": 375, "config": "4"},
    {"Node_A": 149, "Node_B": 1, "Length_ft": 400, "config": "1"},
    {"Node_A": 152, "Node_B": 52, "Length_ft": 400, "config": "1"},
    {"Node_A": 1601, "Node_B": 67, "Length_ft": 350, "config": "6"},
    {"Node_A": 197, "Node_B": 101, "Length_ft": 250, "config": "3"},
    # switches: closed
    {"Node_A": 13, "Node_B": 152, "Length_ft": 1, "config": "1"},
    {"Node_A": 18, "Node_B": 135, "Length_ft": 1, "config": "2"},
    {"Node_A": 60, "Node_B": 160, "Length_ft": 1, "config": "3"},
    {"Node_A": 61, "Node_B": 611, "Length_ft": 1, "config": "5"},
    {"Node_A": 97, "Node_B": 197, "Length_ft": 1, "config": "3"},
    {"Node_A": 1501, "Node_B": 149, "Length_ft": 1, "config": "1"}, # 150-149
    # switches: open
    # {"Node_A": 250, "Node_B": 251, "Length_ft": 1, "config": "2"},
    # {"Node_A": 450, "Node_B": 451, "Length_ft": 1, "config": "3"},
    # {"Node_A": 54, "Node_B": 94, "Length_ft": 1, "config": "1"},
    # {"Node_A": 151, "Node_B": 300, "Length_ft": 1, "config": "4"},
    # {"Node_A": 300, "Node_B": 350, "Length_ft": 1, "config": "3"},
    # voltage regulators:
    # ---
    {"Node_A": 150, "Node_B": 1501, "Length_ft": 0, "config": "VReg1"}, # 150-149
    # {"Node_A": 150, "Node_B": 1501, "Length_ft": 1, "config": "1"}, # 150-149
    # ---
    {"Node_A": 9, "Node_B": 901, "Length_ft": 0, "config": "VReg2"},
    # {"Node_A": 9, "Node_B": 901, "Length_ft": 1, "config": "9"},
    # ---
    {"Node_A": 25, "Node_B": 2501, "Length_ft": 0, "config": "VReg3"},
    # {"Node_A": 25, "Node_B": 2501, "Length_ft": 1, "config": "7"},
    # ---
    {"Node_A": 160, "Node_B": 1601, "Length_ft": 0, "config": "VReg4"}, # 160-67
    # {"Node_A": 160, "Node_B": 1601, "Length_ft": 1, "config": "6"}, # 160-67
    # ---
]


transformer_data = [
    # {
    #     "Name": "Substation",
    #     "kVA": 5000,
    #     "kV_high": 115,
    #     "high_winding_connect": "D",
    #     "kV_low": 4.16,
    #     "low_winding_connect": "GrY",
    #     "R_percent_pu": 1,
    #     "X_percent_pu": 8,
    # },
    {
        "Name": "XFM-1",
        "kVA": 150,
        "kV_high": 4.16,
        "high_winding_connect": "D",
        "kV_low": 0.48,
        "low_winding_connect": "D",
        "R_percent_pu": 1.27,
        "X_percent_pu": 2.72,
    },
    # {
    #     "Name": "XFM-1",
    #     "kVA": 150,
    #     "kV_high": 4.16,
    #     "high_winding_connect": "GrY",
    #     "kV_low": 0.48,
    #     "low_winding_connect": "GrY",
    #     "R_percent_pu": 1.27,
    #     "X_percent_pu": 2.72,
    # },
]
nom_V = 4.16 / np.sqrt(3)
nom_V_xmer = 0.48 / np.sqrt(3)

capacitor_data = [
    {
        "Node": 83,
        "power": {"A": 200, "B": 200, "C": 200},
        "nominal_voltage": {"A": nom_V, "B": nom_V, "C": nom_V},
        "connection": "Y",
    },
    {
        "Node": 88,
        "power": {"A": 50},
        "nominal_voltage": {"A": nom_V},
        "connection": "Y",
    },
    {
        "Node": 90,
        "power": {"B": 50},
        "nominal_voltage": {"B": nom_V},
        "connection": "Y",
    },
    {
        "Node": 92,
        "power": {"C": 50},
        "nominal_voltage": {"C": nom_V},
        "connection": "Y",
    },
]


spot_load_data = [
    {
        "Node": 1,
        "Model": "Y_PQ",
        "active_power": {"A": 40},
        "reactive_power": {"A": 20},
        "nominal_voltage": {"A": nom_V},
    },
    {
        "Node": 2,
        "Model": "Y_PQ",
        "active_power": {"B": 20},
        "reactive_power": {"B": 10},
        "nominal_voltage": {"B": nom_V},
    },
    {
        "Node": 4,
        "Model": "Y_PQ",
        "active_power": {"C": 40},
        "reactive_power": {"C": 20},
        "nominal_voltage": {"C": nom_V},
    },
    {
        "Node": 5,
        "Model": "Y_I",
        "active_power": {"C": 20},
        "reactive_power": {"C": 10},
        "nominal_voltage": {"C": nom_V},
    },
    {
        "Node": 6,
        "Model": "Y_Z",
        "active_power": {"C": 40},
        "reactive_power": {"C": 20},
        "nominal_voltage": {"C": nom_V},
    },
    {
        "Node": 7,
        "Model": "Y_PQ",
        "active_power": {"A": 20},
        "reactive_power": {"A": 10},
        "nominal_voltage": {"A": nom_V},
    },
    {
        "Node": 9,
        "Model": "Y_PQ",
        "active_power": {"A": 40},
        "reactive_power": {"A": 20},
        "nominal_voltage": {"A": nom_V},
    },
    {
        "Node": 10,
        "Model": "Y_I",
        "active_power": {"A": 20},
        "reactive_power": {"A": 10},
        "nominal_voltage": {"A": nom_V},
    },
    {
        "Node": 11,
        "Model": "Y_Z",
        "active_power": {"A": 40},
        "reactive_power": {"A": 20},
        "nominal_voltage": {"A": nom_V},
    },
    {
        "Node": 12,
        "Model": "Y_PQ",
        "active_power": {"B": 20},
        "reactive_power": {"B": 10},
        "nominal_voltage": {"B": nom_V},
    },
    {
        "Node": 16,
        "Model": "Y_PQ",
        "active_power": {"C": 40},
        "reactive_power": {"C": 20},
        "nominal_voltage": {"C": nom_V},
    },
    {
        "Node": 17,
        "Model": "Y_PQ",
        "active_power": {"C": 20},
        "reactive_power": {"C": 10},
        "nominal_voltage": {"C": nom_V},
    },
    {
        "Node": 19,
        "Model": "Y_PQ",
        "active_power": {"A": 40},
        "reactive_power": {"A": 20},
        "nominal_voltage": {"A": nom_V},
    },
    {
        "Node": 20,
        "Model": "Y_I",
        "active_power": {"A": 40},
        "reactive_power": {"A": 20},
        "nominal_voltage": {"A": nom_V},
    },
    {
        "Node": 22,
        "Model": "Y_Z",
        "active_power": {"B": 40},
        "reactive_power": {"B": 20},
        "nominal_voltage": {"B": nom_V},
    },
    {
        "Node": 24,
        "Model": "Y_PQ",
        "active_power": {"C": 40},
        "reactive_power": {"C": 20},
        "nominal_voltage": {"C": nom_V},
    },
    {
        "Node": 28,
        "Model": "Y_I",
        "active_power": {"A": 40},
        "reactive_power": {"A": 20},
        "nominal_voltage": {"A": nom_V},
    },
    {
        "Node": 29,
        "Model": "Y_Z",
        "active_power": {"A": 40},
        "reactive_power": {"A": 20},
        "nominal_voltage": {"A": nom_V},
    },
    {
        "Node": 30,
        "Model": "Y_PQ",
        "active_power": {"C": 40},
        "reactive_power": {"C": 20},
        "nominal_voltage": {"C": nom_V},
    },
    {
        "Node": 31,
        "Model": "Y_PQ",
        "active_power": {"C": 20},
        "reactive_power": {"C": 10},
        "nominal_voltage": {"C": nom_V},
    },
    {
        "Node": 32,
        "Model": "Y_PQ",
        "active_power": {"C": 20},
        "reactive_power": {"C": 10},
        "nominal_voltage": {"C": nom_V},
    },
    {
        "Node": 33,
        "Model": "Y_I",
        "active_power": {"A": 40},
        "reactive_power": {"A": 20},
        "nominal_voltage": {"A": nom_V},
    },
    {
        "Node": 34,
        "Model": "Y_Z",
        "active_power": {"C": 40},
        "reactive_power": {"C": 20},
        "nominal_voltage": {"C": nom_V},
    },
    {
        "Node": 35,
        "Model": "D_PQ",
        "active_power": {"AB": 40},
        "reactive_power": {"AB": 20},
        "nominal_voltage": {"A": nom_V, "B": nom_V},
    },
    {
        "Node": 37,
        "Model": "Y_Z",
        "active_power": {"A": 40},
        "reactive_power": {"A": 20},
        "nominal_voltage": {"A": nom_V},
    },
    {
        "Node": 38,
        "Model": "Y_I",
        "active_power": {"B": 20},
        "reactive_power": {"B": 10},
        "nominal_voltage": {"B": nom_V},
    },
    {
        "Node": 39,
        "Model": "Y_PQ",
        "active_power": {"B": 20},
        "reactive_power": {"B": 10},
        "nominal_voltage": {"B": nom_V},
    },
    {
        "Node": 41,
        "Model": "Y_PQ",
        "active_power": {"C": 20},
        "reactive_power": {"C": 10},
        "nominal_voltage": {"C": nom_V},
    },
    {
        "Node": 42,
        "Model": "Y_PQ",
        "active_power": {"A": 20},
        "reactive_power": {"A": 10},
        "nominal_voltage": {"A": nom_V},
    },
    {
        "Node": 43,
        "Model": "Y_Z",
        "active_power": {"B": 40},
        "reactive_power": {"B": 20},
        "nominal_voltage": {"B": nom_V},
    },
    {
        "Node": 45,
        "Model": "Y_I",
        "active_power": {"A": 20},
        "reactive_power": {"A": 10},
        "nominal_voltage": {"A": nom_V},
    },
    {
        "Node": 46,
        "Model": "Y_PQ",
        "active_power": {"A": 20},
        "reactive_power": {"A": 10},
        "nominal_voltage": {"A": nom_V},
    },
    {
        "Node": 47,
        "Model": "Y_I",
        "active_power": {"A": 35, "B": 35, "C": 35},
        "reactive_power": {"A": 25, "B": 25, "C": 25},
        "nominal_voltage": {"A": nom_V, "B": nom_V, "C": nom_V},
    },
    {
        "Node": 48,
        "Model": "Y_Z",
        "active_power": {"A": 70, "B": 70, "C": 70},
        "reactive_power": {"A": 50, "B": 50, "C": 50},
        "nominal_voltage": {"A": nom_V, "B": nom_V, "C": nom_V},
    },
    {
        "Node": 49,
        "Model": "Y_PQ",
        "active_power": {"A": 35, "B": 70, "C": 35},
        "reactive_power": {"A": 25, "B": 50, "C": 20},
        "nominal_voltage": {"A": nom_V, "B": nom_V, "C": nom_V},
    },
    {
        "Node": 50,
        "Model": "Y_PQ",
        "active_power": {"C": 40},
        "reactive_power": {"C": 20},
        "nominal_voltage": {"C": nom_V},
    },
    {
        "Node": 51,
        "Model": "Y_PQ",
        "active_power": {"A": 20},
        "reactive_power": {"A": 10},
        "nominal_voltage": {"A": nom_V},
    },
    {
        "Node": 52,
        "Model": "Y_PQ",
        "active_power": {"A": 40},
        "reactive_power": {"A": 20},
        "nominal_voltage": {"A": nom_V},
    },
    {
        "Node": 53,
        "Model": "Y_PQ",
        "active_power": {"A": 40},
        "reactive_power": {"A": 20},
        "nominal_voltage": {"A": nom_V},
    },
    {
        "Node": 55,
        "Model": "Y_Z",
        "active_power": {"A": 20},
        "reactive_power": {"A": 10},
        "nominal_voltage": {"A": nom_V},
    },
    {
        "Node": 56,
        "Model": "Y_PQ",
        "active_power": {"B": 20},
        "reactive_power": {"B": 10},
        "nominal_voltage": {"B": nom_V},
    },
    {
        "Node": 58,
        "Model": "Y_I",
        "active_power": {"B": 20},
        "reactive_power": {"B": 10},
        "nominal_voltage": {"B": nom_V},
    },
    {
        "Node": 59,
        "Model": "Y_PQ",
        "active_power": {"B": 20},
        "reactive_power": {"B": 10},
        "nominal_voltage": {"B": nom_V},
    },
    {
        "Node": 60,
        "Model": "Y_PQ",
        "active_power": {"A": 20},
        "reactive_power": {"A": 10},
        "nominal_voltage": {"A": nom_V},
    },
    {
        "Node": 62,
        "Model": "Y_Z",
        "active_power": {"C": 40},
        "reactive_power": {"C": 20},
        "nominal_voltage": {"C": nom_V},
    },
    {
        "Node": 63,
        "Model": "Y_PQ",
        "active_power": {"A": 40},
        "reactive_power": {"A": 20},
        "nominal_voltage": {"A": nom_V},
    },
    {
        "Node": 64,
        "Model": "Y_I",
        "active_power": {"B": 75},
        "reactive_power": {"B": 35},
        "nominal_voltage": {"B": nom_V},
    },
    {
        "Node": 65,
        "Model": "D_Z",
        "active_power": {"AB": 35, "BC": 35, "CA": 70},
        "reactive_power": {"AB": 25, "BC": 25, "CA": 50},
        "nominal_voltage": {"A": nom_V, "B": nom_V, "C": nom_V},
    },
    {
        "Node": 66,
        "Model": "Y_PQ",
        "active_power": {"C": 75},
        "reactive_power": {"C": 35},
        "nominal_voltage": {"C": nom_V},
    },
    {
        "Node": 68,
        "Model": "Y_PQ",
        "active_power": {"A": 20},
        "reactive_power": {"A": 10},
        "nominal_voltage": {"A": nom_V},
    },
    {
        "Node": 69,
        "Model": "Y_PQ",
        "active_power": {"A": 40},
        "reactive_power": {"A": 20},
        "nominal_voltage": {"A": nom_V},
    },
    {
        "Node": 70,
        "Model": "Y_PQ",
        "active_power": {"A": 20},
        "reactive_power": {"A": 10},
        "nominal_voltage": {"A": nom_V},
    },
    {
        "Node": 71,
        "Model": "Y_PQ",
        "active_power": {"A": 40},
        "reactive_power": {"A": 20},
        "nominal_voltage": {"A": nom_V},
    },
    {
        "Node": 73,
        "Model": "Y_PQ",
        "active_power": {"C": 40},
        "reactive_power": {"C": 20},
        "nominal_voltage": {"C": nom_V},
    },
    {
        "Node": 74,
        "Model": "Y_Z",
        "active_power": {"C": 40},
        "reactive_power": {"C": 20},
        "nominal_voltage": {"C": nom_V},
    },
    {
        "Node": 75,
        "Model": "Y_PQ",
        "active_power": {"C": 40},
        "reactive_power": {"C": 20},
        "nominal_voltage": {"C": nom_V},
    },
    {
        "Node": 76,
        "Model": "D_I",
        "active_power": {"AB": 105, "BC": 70, "CA": 70},
        "reactive_power": {"AB": 80, "BC": 50, "CA": 50},
        "nominal_voltage": {"A": nom_V, "B": nom_V, "C": nom_V},
    },
    {
        "Node": 77,
        "Model": "Y_PQ",
        "active_power": {"B": 40},
        "reactive_power": {"B": 20},
        "nominal_voltage": {"B": nom_V},
    },
    {
        "Node": 79,
        "Model": "Y_Z",
        "active_power": {"A": 40},
        "reactive_power": {"A": 20},
        "nominal_voltage": {"A": nom_V},
    },
    {
        "Node": 80,
        "Model": "Y_PQ",
        "active_power": {"B": 40},
        "reactive_power": {"B": 20},
        "nominal_voltage": {"B": nom_V},
    },
    {
        "Node": 82,
        "Model": "Y_PQ",
        "active_power": {"A": 40},
        "reactive_power": {"A": 20},
        "nominal_voltage": {"A": nom_V},
    },
    {
        "Node": 83,
        "Model": "Y_PQ",
        "active_power": {"C": 20},
        "reactive_power": {"C": 10},
        "nominal_voltage": {"C": nom_V},
    },
    {
        "Node": 84,
        "Model": "Y_PQ",
        "active_power": {"C": 20},
        "reactive_power": {"C": 10},
        "nominal_voltage": {"C": nom_V},
    },
    {
        "Node": 85,
        "Model": "Y_PQ",
        "active_power": {"C": 40},
        "reactive_power": {"C": 20},
        "nominal_voltage": {"C": nom_V},
    },
    {
        "Node": 86,
        "Model": "Y_PQ",
        "active_power": {"B": 20},
        "reactive_power": {"B": 10},
        "nominal_voltage": {"B": nom_V},
    },
    {
        "Node": 87,
        "Model": "Y_PQ",
        "active_power": {"B": 40},
        "reactive_power": {"B": 20},
        "nominal_voltage": {"B": nom_V},
    },
    {
        "Node": 88,
        "Model": "Y_PQ",
        "active_power": {"A": 40},
        "reactive_power": {"A": 20},
        "nominal_voltage": {"A": nom_V},
    },
    {
        "Node": 90,
        "Model": "Y_I",
        "active_power": {"B": 40},
        "reactive_power": {"B": 20},
        "nominal_voltage": {"B": nom_V},
    },
    {
        "Node": 92,
        "Model": "Y_PQ",
        "active_power": {"C": 40},
        "reactive_power": {"C": 20},
        "nominal_voltage": {"C": nom_V},
    },
    {
        "Node": 94,
        "Model": "Y_PQ",
        "active_power": {"A": 40},
        "reactive_power": {"A": 20},
        "nominal_voltage": {"A": nom_V},
    },
    {
        "Node": 95,
        "Model": "Y_PQ",
        "active_power": {"B": 20},
        "reactive_power": {"B": 10},
        "nominal_voltage": {"B": nom_V},
    },
    {
        "Node": 96,
        "Model": "Y_PQ",
        "active_power": {"B": 20},
        "reactive_power": {"B": 10},
        "nominal_voltage": {"B": nom_V},
    },
    {
        "Node": 98,
        "Model": "Y_PQ",
        "active_power": {"A": 40},
        "reactive_power": {"A": 20},
        "nominal_voltage": {"A": nom_V},
    },
    {
        "Node": 99,
        "Model": "Y_PQ",
        "active_power": {"B": 40},
        "reactive_power": {"B": 20},
        "nominal_voltage": {"B": nom_V},
    },
    {
        "Node": 100,
        "Model": "Y_Z",
        "active_power": {"C": 40},
        "reactive_power": {"C": 20},
        "nominal_voltage": {"C": nom_V},
    },
    {
        "Node": 102,
        "Model": "Y_PQ",
        "active_power": {"C": 20},
        "reactive_power": {"C": 10},
        "nominal_voltage": {"C": nom_V},
    },
    {
        "Node": 103,
        "Model": "Y_PQ",
        "active_power": {"C": 40},
        "reactive_power": {"C": 20},
        "nominal_voltage": {"C": nom_V},
    },
    {
        "Node": 104,
        "Model": "Y_PQ",
        "active_power": {"C": 40},
        "reactive_power": {"C": 20},
        "nominal_voltage": {"C": nom_V},
    },
    {
        "Node": 106,
        "Model": "Y_PQ",
        "active_power": {"B": 40},
        "reactive_power": {"B": 20},
        "nominal_voltage": {"B": nom_V},
    },
    {
        "Node": 107,
        "Model": "Y_PQ",
        "active_power": {"B": 40},
        "reactive_power": {"B": 20},
        "nominal_voltage": {"B": nom_V},
    },
    {
        "Node": 109,
        "Model": "Y_PQ",
        "active_power": {"A": 40},
        "reactive_power": {"A": 20},
        "nominal_voltage": {"A": nom_V},
    },
    {
        "Node": 111,
        "Model": "Y_PQ",
        "active_power": {"A": 20},
        "reactive_power": {"A": 10},
        "nominal_voltage": {"A": nom_V},
    },
    {
        "Node": 112,
        "Model": "Y_I",
        "active_power": {"A": 20},
        "reactive_power": {"A": 10},
        "nominal_voltage": {"A": nom_V},
    },
    {
        "Node": 113,
        "Model": "Y_Z",
        "active_power": {"A": 40},
        "reactive_power": {"A": 20},
        "nominal_voltage": {"A": nom_V},
    },
    {
        "Node": 114,
        "Model": "Y_PQ",
        "active_power": {"A": 20},
        "reactive_power": {"A": 10},
        "nominal_voltage": {"A": nom_V},
    },
]

source_data = [
    {
        "Node": 150,
        # "Node": 1501,
        "nominal_voltage": {
            "A": 4.16/np.sqrt(3),
            "B": 4.16/np.sqrt(3),
            "C": 4.16/np.sqrt(3),
        },
        "source_type": "ConstantVoltage",
    },
#     {
#         "Node": 150,
#         # "Node": 1501,
#         "nominal_voltage": {
#             "A": 4.16/np.sqrt(3),
#             "B": 4.16/np.sqrt(3),
#             "C": 4.16/np.sqrt(3),
            
#         },
#         "source_type": "ConstantSeqVoltage",
#     }
]

volt_reg_data = [
    {
        "Name": "VReg1",
        "bandwidth": 2,   # in Volts
        "PT_ratio": 20,
        "CT_primary": 700,
        "CT_secondary": 5,
        "voltage_level": {"A": 120},
        "R_setting": {"A": 3},
        "X_setting": {"A": 7.5},
        "nominal_voltage": {"A": 2.401777, "B": 2.401777, "C": 2.401777},
        "control": "manual",
        "tap_setting": {"A": 7, "B": 7, "C": 7},
        # "control": "automatic",
        # "tap_setting": {"A": 0, "B": 0, "C": 0},
    },
    {
        "Name": "VReg2",
        "bandwidth": 2,   # in Volts
        "PT_ratio": 20,
        "CT_primary": 50,
        "CT_secondary": 5,
        "voltage_level": {"A": 120},
        "R_setting": {"A": 0.4},
        "X_setting": {"A": 0.4},
        "nominal_voltage": {"A": 2.401777},
        "control": "manual",
        "tap_setting": {"A": -1},
        # "control": "automatic",
        # "tap_setting": {"A": 0},
    },
    {
        "Name": "VReg3",
        "bandwidth": 1,   # in Volts
        "PT_ratio": 20,
        "CT_primary": 50,
        "CT_secondary": 5,
        "voltage_level": {"A": 120, "C": 120},
        "R_setting": {"A": 0.4, "C": 0.4},
        "X_setting": {"A": 0.4, "C": 0.4},
        "nominal_voltage": {"A": 2.401777, "C": 2.401777},
        "control": "manual",
        "tap_setting": {"A": 0, "C": -1},
        # "control": "automatic",
        # "tap_setting": {"A": 0, "C": 0},
    },
    {
        "Name": "VReg4",
        "bandwidth": 2,   # in Volts
        "PT_ratio": 20,
        "CT_primary": 300,
        "CT_secondary": 5,
        "voltage_level": {"A": 124, "B": 124, "C": 124},
        "R_setting": {"A": 0.6, "B": 1.4, "C": 0.2},
        "X_setting": {"A": 1.3, "B": 2.6, "C": 1.4},
        "nominal_voltage": {"A": 2.401777, "B": 2.401777, "C": 2.401777},
        "control": "manual",
        "tap_setting": {"A": 8, "B": 1, "C": 5},
        # "control": "automatic",
        # "tap_setting": {"A": 0, "B": 0, "C": 0},
    }
]
inverter_data = []
generator_data = []
dist_load_data = []
